locustfile = ./scenarios/http/gateway/existing_user_get_operations/scenario.py
spawn-rate = 12
run-time = 3m
headless = true
users = 120
html = ./scenarios/http/gateway/existing_user_get_operations/report.html
